inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 3.0
  DisabledByDefault: true
  NewCops: disable
  SuggestExtensions: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: true

Metrics/ClassLength:
  Max: 5000

Metrics/ParameterLists:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Rails/UnknownEnv:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

# Use only ascii symbols in comments.
Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineBlockParams:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
