name: Rails

on:
  push:

defaults:
  run:
    shell: bash
    working-directory: backend

env:
  RAILS_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          TZ: "Asia/Tokyo"
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping" --health-interval 20s --health-timeout 10s --health-retries 10

    steps:
    - uses: actions/checkout@v2

    - name: Set database.yml
      run: cp -v config/database.ci.yml config/database.yml

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    - name: Cache gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Migration
      run: bundle exec rails db:schema:load --trace

    - name: Run rspec
      run: bundle exec rspec

    - name: Run rubocop
      run: bundle exec rubocop --parallel
